### ISSUE TITLE
We might want some sort of scaling of the target

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#183]
Simplest case: log scaling in regression.

It is really strange if we can not properly do this from within the pipelines.

**Comment by mb706** [comment]
This is a tricky problem, because there should really be two pipeops:
1) the PipeOp that takes a log of the task's target
2) the PipeOp that takes an exp of the prediction

Also, for (2), we might want to correct the prediction if "se" values are available, because `exp(E[x]) < E[exp(x)]` (Jensen's Inequality).

**Comment by pfistfl** [comment]
duplicate, closing here.
