### ISSUE TITLE
PipeOpCopy: unclear documentation

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3pipelines#196]
#'   Copies its input `outnum` times. This should usually not be needed,
#'   because copying happens automatically.

I get the first part, but the second sentence let me wonder why we have this PipeOp. Maybe we can rephrase this. Or is the PO really obsolete?

**Comment by berndbischl** [comment]
@mb706 wants to discuss to maybe delete it

**Comment by berndbischl** [comment]
mark this for dicussion for the sprint pls

**Comment by mb706** [comment]
It can be useful if we want to use the `%>>%` operator. E.g. to get the graph
```
A---X

B---Y
 \
  --Z
```
we can not do `gunion(list(A, B)) %>>% gunion(list(X, Y, Z))`, but we can do `gunion(list(A, B %>>% PipeOpCopy$new(2))) %>>% gunion(list(X, Y, Z))`. It is similar to the NULL PipeOP in that you usually don't need it unless you want to make something explicit that otherwise happens implicitly.

**Comment by mb706** [comment]
To Do: document why this is useful.
