### ISSUE TITLE
Learner based imputation PipeOp

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#262]
Should be easy with the neat `PipeOpImpute` base class.

**Comment by prockenschaub** [comment]
Would this simply be a single imputation based on mean predictions by a learner? With a little guidance to keep in line with the overall package design I would be happy to take that on.

Could this be extended to multiple imputation? I need to include MI in my modelling workflow and would be very interested to see/create a PipeOp for this. This would most likely result in a branched workflow with one flow per imputed dataset, which later will have to be "unbranched"?

**Comment by mb706** [comment]
Yes, the plan is to inherit from [PipeOpImpute](https://github.com/mlr-org/mlr3pipelines/blob/master/R/PipeOpImpute.R) with a `PipeOp` that is constructed with a `Learner` and to some degree works similarly to `PipeOpLearner`. I think this would be quite an advanced thing to implement properly; if you feel up to the task you can try it, otherwise I would propably get around to it within maybe a month.

MI is an interesting Idea; if the `Learner` is inherently stochastic it would be possible to do something
```r
po("copy", n) %>>%
  greplicate(
    po("imputelrn", imputelearner) %>>%
    po("learner", predictlearner),
  n) %>>%
  po("classif.avg")
```
It may be useful to introduce noise according to `"prob"` or `"se"` prediction, that could be a `PipeOp` as well.

**Comment by prockenschaub** [comment]
I gave it a first shot and created a `PipeOpImputeLearner` class. 

My implementation is modelled very similar to `PipeOpImputeMean` but uses `train` and `predict` of a `Learner` to obtain the mean instead of `mean(feature, na.rm = TRUE)`. The learner acts on the context (all variables indicated as predictors for the imputation), which we use to create a temporary imputation task.

```r
train_imputer = function(feature, type, context) {
    context$impute_col = feature
    task = TaskRegr$new(id = "taskimpute", backend = context, target = "impute_col")
    
    private$.learner$train(task)
    pred = private$.learner$predict(task)
    pred   # Return a prediction object instead of a single mean
}
```

The learner is passed as second in the initializer function and stored as a private variable, similar to what happens in `PipeOpLearner`. The initializer of `PipeOpImp` is called with `whole_task_dependent = TRUE` to provide the context in `train_imputer`.

```r
initialize = function(id = "imputelearner", learner, param_vals = list()) {
    private$.learner = as_learner(learner)$clone(deep = TRUE) 
    super$initialize(id, param_vals = param_vals, whole_task_dependent = TRUE)
}
```

Finally, we use the prediction object to get a mean prediction for each missing value. 

```r
impute = function(feature, type, model, context) {
    feature[is.na(feature)] = model$response[is.na(feature)]   # Impute missing values with prediction
    feature
}
```

I have omitted a few extra sanity checks and edge cases (e.g. a completely missing column) for readability. Does that look broadly sensible? Am I missing something obvious?

With the quick and dirty implementation I can see the following issues/limitations:
* Only one variable type can be imputed at once (classification or regression). This could be extended but it is probably better to keep the implementation simple and require two `po` to impute numeric and categorical variables separately. The `select_col` function would have to be adjusted accordingly to select the right variable type based on the classifier. 
* Columns used for the learner must not contain missing values themselves. Options include a) only using complete columns to train the learner or b) copy columns with missing values, replace their missing values with a simpler method (e.g. mean imputation), and use these columns as the predictors in the learner rather than the original columns. Neither ot these options is ideal and I would prefer something akin to the chained equations used in multiple imputation. However, chained equations do not seem to fit into the current framework.
* As you mentoined, it would be beneficial to add some noise to the imputated values, particularly when thinking ahead for at multiple imputation. Would you simple add noise based on a local gaussian approximation based on `se` or `prob`?

**Comment by prockenschaub** [comment]
I would have some time this week to finish at least a first version incl. tests. Shall I just create a pull request once I am finished?

I am also trying to include mlr3pipelines into the workflow of a current project I am working on, so I would be more than happy to contribute further. What would be the best way to go about this, i.e. just pick some issues I like from the issues page in order of tagged priority or can you give some pointers towards what would be helpful? Does it make sense to join the slack channel?

**Comment by mb706** [comment]
#386 fixes this
