### ISSUE TITLE
Naming: PipeOpLearnerCV

### ISSUE THREAD

**Issue by Coorsaa** [mlr-org/mlr3pipelines#276]
`po("learnercv", ...)` would be more consistent to all other pipeops than `po("learner_cv", ...)`

**Comment by mb706** [comment]
I agree, but maybe @berndbischl and @mllg want to give their opionion: How should the naming scheme of `PipeOp`s be? Currently it is (with `"learner_cv"` the exception) just one word; mlr3 appears to be using periods, other options are camel case, underscores, etc.

Something that may be relevant: Currently when constructing a `GraphLearner` from a `Graph` the `id` of that `Learner` is just the `id`s of each `PipeOp` concatenated by a period, so I'd suggest to use underscores if we decide to use separators
```r
as_learner(po("scale") %>>% lrn("classif.rpart"))
#> <GraphLearner:scale.classif.rpart>
```

Options:
* One word (current): `scale`, `spatialsign`, `modelmatrix`, `imputemedian`, `encodelmer`, `learnercv`
* Underscore sep in most places where they would be separating words:  `scale`, `spatial_sign`, `model_matrix`, `impute_median`, `encode_lmer`, `learner_cv`
* Underscore sep in places where there is a grouping of `PipeOp`s (because there are different "encode", "impute" etc. `PipeOp`s, also there exist both `learner` and `learner_cv`):  `scale`, `spatialsign`, `modelmatrix`, `impute_median`, `encode_lmer`, `learner_cv`

**Comment by mllg** [comment]
mlr3 uses periods to separate the "type" from the id, and underscores otherwise. `"classif.random_forest"` instead of `"classif.random.forest"`. I'm not super happy with this, and we could get rid of the underscore.

@berndbischl ?

**Comment by mb706** [comment]
decision: Names should be with underscores. Actions:
1. add new names with underscores as alternative names in dictionary
2. after a while, add a deprecation warning when old names are used
3. after a further while, remove the old names
