### ISSUE TITLE
ExtraPipeOps package

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#288]
At some point we may want to put some less frequently used pipeops in their own package. Should we do this? How would we organize this: which pipeops stay in mlr3pipeops, which go to the mlr3extrapipes package, maybe some should go in their own repo? Should pipelines (#277 ) get their own package? Do you have an opinion here @mllg @berndbischl @pfistfl ?

**Comment by berndbischl** [comment]
At some point. Maybe. But we are not there yet. Let's stabilize first pls

**Comment by mllg** [comment]
What pipeops would you consider as being not important enough for the package? I get your point, but please consider that

1. pipeops for special tasks can go into the respective package (e.g., survival pipeops into mlr3survival), and
2.  we are not in the same situation as with mlr3learners. We opted to have one forest implementation instead of 5, but you are still able to fit a random forest. Do we have pipeops which basically do the same, but are just implemented differently?

Pipelines could maybe just get their own dictionary instead of their own package. I'm still unsure where this will end though:

* general preproc pipelines
* preproc pipelines constructed for specific learners, with or without the learner
* pipelines which are self-tuning, automl-like learners

?

**Comment by pfistfl** [comment]
Hey,

I initiated this conversation with @mb706.
agree that this can wait, but maybe not too long. 

1) I think we are already starting to develop PipeOp's that are rarely used. 

2) I think we could save a lot of time by demanding that only things that are "standard" go into 
mlr3pipelines, the rest goes to `extrapipes`.

3) We want mlr3pipelines to have few dependencies, but also a low number of suggested
    packages (to run unit tests etc.).
    If I now add a PipeOp that uses `tensorflow` under the hood, this might become difficult very fast.

4) We might want to create a path where people can add their own PipeOp's, i.e. involve the community. 

> pipeops for special tasks can go into the respective package (e.g., survival pipeops into mlr3survival), and

Have we clearly defined a hierarchy, of what depends/builds on what, or how packages should interact with each other?
Does `mlr3survival` depend / suggest `mlr3pipelines` now? Or vice versa?


> do the same, but are just implemented differently?
- We have for example like 5 imputation methods

**Comment by berndbischl** [comment]
> 1. I think we are already starting to develop PipeOp's that are rarely used.

well. thats a problem in itself. pls do not do this. focus on the fundamentals

**Comment by berndbischl** [comment]
i do agree that we have to find a system here for the future, i understand the nature of the thread.

**Comment by berndbischl** [comment]
maybe we discuss this also in a core call?

**Comment by pfistfl** [comment]
Additional thought: 
A lot of packages will depend on `mlr3pipelines`.
If anything breaks in `Pipelines` this will become a nuisance upstream. 
I guess this is a really good argument for pushing out as many things as possible.

**Comment by mb706** [comment]
I think we should do this once it becomes an issue.
