### ISSUE TITLE
ExtractDateFeatures PipeOp

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#303]
We currently have no real way of dealing with columns of type `POSIXct`.
A set of features (+ implementation) that can be extracted from a `POSIXct` column can be found in 
[fast.ai](https://github.com/fastai/fastai/blob/master/fastai/tabular/transform.py).

**TODO: Implement a PipeOpDateFeatures**

Functionality:
Extracts a set of `numeric / logical / factor` features from a `POSIXct` column.
- Features to extract:
  - See fast.ai link
  - hour / minute / second
  - night/day, i.e. whether time (or hour) is in [6:00 am - 8:00pm] or not
  - other ideas?

Params: 
- A column name to operate on. (Check whether this is of the correct type).
 ~~A logical flag for each date feature (whether this should be extracted or not)~~ # maybe do this later
- ~~A logical flag: Whether to remove constant features (default: TRUE)~~

Caveats:
- Try to not introduce additional (or as little as possible) package dependencies.
- Removing constant features: Extract all functions, check whether any columns are constant.
  Make sure, that the colnames extracted are equal in `train/predict`, i.e. we have to store a 
  vector of `colnames` used in `train` to only extract those features during prediction.
  `PipeOpRemoveConstants` can guide you there.

Open Question:
Do we want to have removing constants embedded in this `PipeOp` or just force the user to always
use `PipeOpRemoveConstants` afterwards.

**Comment by sumny** [comment]
Should this only work for objects of class `Date`? If we directly implement this for objects of class `POSIXct`, `Dates` are supported but also hours, minutes and seconds would be available as features.

**Comment by pfistfl** [comment]
Currently `mlr3` supports dates of type `pxc = "POSIXct"`. 
I would assume we should work on it. 
I will update the specs above.

**Comment by sumny** [comment]
So I drafted an early version that can be found in the `pipeop_datefeatures` branch.
Currently supports:
  - year
  - month
  - week of the year
  - day of the year
  - day of the month
  - day of the week
  - hour
  - minute
  - second
  - night/day (whether hour is in 6.00 am - 08.00pm)

Currently, all engineered features are numeric except for `is_day` which is logical. I guess this needs some discussion, i.e., most of them could also be ordered factors? I think fast.ai simply returns numeric features (?)

If `cyclic = TRUE` the respective features are replaced by cyclic ones, i.e., sinus and cosinus transformations of 2 * pi * x / max(x) where x ist the original feature, i.e., `minute`.

Currently, constant features are NOT removed, so one must use `PipeOpRemoveConstants` afterwards; this also needs some discussion, I guess.

Also, I did not write any tests yet (I will do this if this PipeOp turns out to be useful).

**Comment by pfistfl** [comment]
See #308

**Comment by mb706** [comment]
> Currently, constant features are NOT removed, so one must use `PipeOpRemoveConstants` afterwards

I prefer this behaviour.

**Comment by pfistfl** [comment]
Merged  in #308
