### ISSUE TITLE
predict_type from last learner not propagated

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#306]
```
library(mlr3)
library(mlr3pipelines)

task = tsk("pima")
learner = lrn("classif.rpart", predict_type = "prob")
resampling = rsmp("holdout")
r = resample(task, learner, resampling)
m = msr("classif.auc")
r$aggregate(m)  # works

pipeline = po("imputemean") %>>% learner
r = resample(task, pipeline, resampling)
r$aggregate(m) # fails
# Error: Measure 'classif.auc' needs predict_type 'prob'

pipeline = po("imputemean") %>>% learner
graphl = GraphLearner$new(pipeline)
graphl$predict_type = "prob" # works but looks tedious
r = resample(task, graphl, resampling)
r$aggregate(m)
```

I ran thru the usecase above. 
1) Where is exactly documented what the line 
graphl$predict_type = "prob" 
does or how predict types in general work for pipelines

2) for my usecase above it seems pretty unintuitive for the user why he has to set the predict_tyoe again? can we simplify this?

**Comment by mb706** [comment]
1. this is not documented explicitly; I guess it is implicit in that (a) a Learner needs a predict_type, which is initialized as "response", (b) every GraphLearner is a Learner (Aristotle would be proud). But yeah should be written somewhere.

2. Unfortunately we can only solve this heuristically, because the last operation may not be a Learner at all (and may in fact be a thresholding pipeop that could change "response" to "prob" predictions). A few solutions I see:

    1. GraphLearner always inspects the last PipeOp; if it is a PipeOpLearner it checks it for a predict_type, otherwise it defaults to "response"
    2. The PipeOp gets a predict_type, so a PipeOpLearner gets its predict_type from the attached Learner, but a PipeOpThreshold can also get a predict_type that may be different
        1. Maybe we give PipeOps an additional predict_type "pass-through" that signals that the previous PipeOp's predict_type should be used. E.g. if the last PipeOp is a prediction averager that maps prob -> prob and response -> response we could cover that case

    What should the behaviour be when a user *changes* `graph$predict_type`, vs. `graph$pipeops$classif.rpart$learner$predict_type`?

**Comment by pfistfl** [comment]
I propose the following design:

* `predict_type` is an AB in every `PipeOp` that returns NULL for almost every `PipeOp`.
* Any PipeOp that changes the `predict_type` has an active binding that reflects this, i.e.
  `PipeOpThreshold` would have `predict_type ==  "response"`.
* Currently the only two `PipeOps` I recall that actually affect the `predict_type` are 
  `PipeOpLearner` and `PipeOpThreshold`.
* `GraphLearners` have exactly one output. This helps us making outputs unambiguous.
* The only situation where this currently fails is for `branch-unbranch` Pipelines. 
  I guess in order to solve this we would need to enforce i.e. predict_types to be similar for all sub-graphs in a branch-unbranch.

**Comment by mb706** [comment]
Solved by https://github.com/mlr-org/mlr3pipelines/pull/457
