### ISSUE TITLE
Behaviour of PipeOpImpute* during predict

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#325]
The following currently does not work

```r
  tsk = tsk("boston_housing")
  lrn = lrn("regr.rpart")

  # missings during predict
 dt = tsk$data()
 dt[2, 3] = NA
 tsk2 = TaskRegr$new(id = "bh", dt, target = "medv")
 lrn$properties = c("multiclass", "twoclass")
 p = po("imputehist", param_vals = list(affect_columns = is.numeric)) %>>% po(lrn)
 g = GraphLearner$new(p)
 g$train(tsk)
 g$predict(tsk2)
 ```

Because, as no data is missing during training no data is imputed during prediction.
I guess we should discuss and implement this.

**Comment by mb706** [comment]
Your bug is `affect_columns`, which should be a `Selector` function that maps a `Task` to a `character` (of selected columns). Replace the offending line with
```r
p = po("imputehist", param_vals = list(affect_columns = selector_type("numeric"))) %>>% po(lrn)
```
and things should work.

Imputation pipeops build an imputation model for all features. If modeling is expensive and you want to limit to columns with missings, you would have to have a selector for that, e.g.
`affect_columns = function(task) names(Filter(identity, task$missings()))`

**Comment by pfistfl** [comment]
I guess we really need to document this stuff, as I did not find it / think stuff through enough.
A good option would be a mlr3gallery post I guess?

**Comment by mb706** [comment]
This is documented in the `?PipeOpTaskPreproc` documentation (Parameters: `affect_columns`) but I agree that this should have thrown an error (#327).

**Comment by mb706** [comment]
We expect our users to always go up the inheritance chain when reading documentation since this would otherwise involve a lot of duplicate text. ("The parameters are the parameters inherited from ‘PipeOpImpute’.")

**Comment by pfistfl** [comment]
I guess this is solved.
I created a tutorial in https://github.com/mlr-org/mlr3gallery/pull/7, and if we merge #323 this should now also error.
