### ISSUE TITLE
trainGraph should be a method of Graph

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#34]
Additionally, it should work on a `Graph`, not a `GraphNode`

**Comment by pfistfl** [comment]
Well,  we have a `train()` method, I think this is sufficient

**Comment by berndbischl** [comment]
no not really. we at LEAST need a consistent policy here. not messily have methods sometimes inside, sometimes defined outside, and with different names.

at least then the names need to match, and the signatures. so that a reader can see AT ONCE that this is actually a method of a class, not something else...

**Comment by berndbischl** [comment]
was refactored
