### ISSUE TITLE
Error creating pipeop learner when using mlr3spatiotempcv package

### ISSUE THREAD

**Issue by mcoghill** [mlr-org/mlr3pipelines#368]

**Comment by mcoghill** [comment]
Whoops my hand slipped when creating this issue, please ignore that mistake!

When the mlr3spatiotempcv package is loaded in the same session, I get this error when trying to create a pipeoplearner: 

```
Error in assert_connection_table(input):
Assertion on ''name' column in input' failed: Contains duplicated values, position 2.
```

The error is absent in a clean session when only the mlr3verse is loaded and a new pipeoplearner is created. I've been able to trace this issue to the [PipeOpLearner function](https://github.com/mlr-org/mlr3pipelines/blob/master/R/PipeOpLearner.R), line 83: 

`task_type = mlr_reflections$task_types[private$.learner$task_type]$task`

Which would normally produce only one value; however with the mlr3spatiotempcv package loaded it produces two values and will result in the error seen above. I've been able to work around this issue simply by loading the mlr3spatiotempcv package after creating the pipeline operator, but this might be something that could be addressed later on.

Thanks for all your hard work!

**Comment by sumny** [comment]
@mcoghill I forgot to comment on this when I pushed the PR. First of all, thank you very much for taking your time to report this bug and already providing a direction for us to look into it. This was caused by `mlr3spatiotempcv` modifying an internal mlr3 object, `mlr_reflections`, in a way we did not anticipate. We provided a hotfix that fixes this bug.
