### ISSUE TITLE
GraphLearner shortcut

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#411]
Currently we have a lot of shortcuts for various things, i.e. `ppl`, `po`, ... 

What I currently still have to write out, and which feels unnatural is
```r
gr = po(...) %>>% lrn("...")
GraphLearner$new(gr)
```

I see two options: a) adding a shortcut or b) doing some form of auto-conversion.
I am still not sure whether we actually wanna do auto-conversion, as this seems very tricky.

**a)** One somewhat simple way to shorten this would be to simply make `mlr3::lrn()` a S3 method:

`lrn.character`: Looks up a learner from a dict.
`lrn.Graph`: constructs a `GraphLearner` from a graph.

This would enable things like 
```r
lrn(flt("variance") %>>% lrn("classif.rpart"))
```

**Comment by pfistfl** [comment]
possibly push this to mlr3, graphlearner is constructed only when used within mlr3

**Comment by mb706** [comment]
`as_learner()`?

**Comment by mb706** [comment]
So we do have `po()` as an S3 method that automatically takes Filters, Selectors etc. The difference between `as_pipeop` and `po()` is that `po()` allows for additional parameters (of the constructed `PipeOp`) to be set. This may be useful, because e.g. the `PipeOpFilter` has options that the filter that is being enclosed does not have. Is the `Learner` a similar situation here? Or is `as_learner()` the only thing we really need? If we want this, mlr3 would have to turn `lrn()` into an S3 method.

**Comment by mb706** [comment]
(I personally think `as_learner()` is enough, but if we *do* want `lrn(<pipeop>)` then this is blocked)

**Comment by mllg** [comment]
Agreeing that `as_learner()` is enough. `lrn()` constructs objects from id, `as_learner()` converts objects.

**Comment by mb706** [comment]
Closing this since noone seems to disagree.
