### ISSUE TITLE
Nested GraphLearners

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#446]
We should perhaps try to avoid nested Graph-Learners. 
What happens here, I guess is that we auto-convert the `GraphLearner` `g1` automatically to a 1-Node `Graph`. 
(I know this is actually a programmer error, but it is transparent / hard to spot and we might be able to just yield the identity instead?

``` r
library(mlr3)
library(mlr3pipelines)
g1 = GraphLearner$new(lrn("classif.rpart"))
GraphLearner$new(g1)$param_set
#> <ParamSetCollection>
#>                                            id    class lower upper levels
#> 1:       classif.rpart.classif.rpart.minsplit ParamInt     1   Inf
#> 2:      classif.rpart.classif.rpart.minbucket ParamInt     1   Inf
#> 3:             classif.rpart.classif.rpart.cp ParamDbl     0     1
#> 4:     classif.rpart.classif.rpart.maxcompete ParamInt     0   Inf
#> 5:   classif.rpart.classif.rpart.maxsurrogate ParamInt     0   Inf
#> 6:       classif.rpart.classif.rpart.maxdepth ParamInt     1    30
#> 7:   classif.rpart.classif.rpart.usesurrogate ParamInt     0     2
#> 8: classif.rpart.classif.rpart.surrogatestyle ParamInt     0     1
#> 9:           classif.rpart.classif.rpart.xval ParamInt     0   Inf
#>           default value
#> 1:             20
#> 2: <NoDefault[3]>
#> 3:           0.01
#> 4:              4
#> 5:              5
#> 6:             30
#> 7:              2
#> 8:              0
#> 9:             10     0
```

<sup>Created on 2020-07-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mb706** [comment]
This is the auto-conversion `Learner` -> `PipeOp` -> `Graph` at work, which `GraphLearner` triggers by calling `as_graph` on its first argument.

I think `GraphLearner$new()` etc. should behave as it does now, because it is consistent. If the user is writing a program that takes a `Learner` from somewhere and expects `GraphLearner$new()` to behave as it does currently regarding hyperparameter names, then he shouldn't have to know whether that object is a `GraphLearner` and handle that for an extra case.

OTOH I can see that unnecessarily nested Graphs can be an annoyance. How about a `GraphLearner$unnest()` and `Graph$unnest()` function that turns a nested `Graph(Learner)` into a flatter structure? I think it would be necessary to keep the hyperparameter names as they are in your example (`classif.rpart.classif.rpart....`) to avoid id clashes, but it would help for parallelization, plotting, and maybe other things that like explicit graphs.

**Comment by pfistfl** [comment]
I think I agree.
I guess the `unnest` thing could be useful even though it might not be in this case.
Will close this for now.
