### ISSUE TITLE
R/mlr_graphs.R missing in the CRAN 0.1.3 release

### ISSUE THREAD

**Issue by wzel** [mlr-org/mlr3pipelines#449]
`R/mlr_graphs.R` exists in the current repo (added in February), but absent from the CRAN release (dated April). This breaks the installation process of [`mlr3ordinal`](https://github.com/mlr-org/mlr3ordinal).

**Comment by wzel** [comment]
There is no release branch nor a release tag for v0.1.3 to investigate whether the exclusion of this file from the release was intentional.

**Comment by pat-s** [comment]
fix from mlr3ordinal: https://github.com/mlr-org/mlr3ordinal/commit/b98ee658541001b74ad70376738d6bf2793a5bb7

**Comment by pfistfl** [comment]
AFAIK, `mlr3ordinal` was never intended to work with the current CRAN version of mlr3pipelines.
Sorry for the confusion regarding versioning etc. I would assume this is fixed by depending on the current github version of mlr3pipelines.

As far as I know, `mlr3ordinal` is not finished, so there might be quite a few breaking changes in the future.

**Comment by pat-s** [comment]
@pfistfl There are multiple issues here. I try to clarify/summarize: 

- Why does `graphs.R` exist but is not avail in the CRAN release from April? There is no reason it needs to be in a CRAN release - but if it exists in the master branch since February (did not check though), this is confusing. Usually users do not check the source code with respect to file creation timestamps - but here it happened 😄 
- {mlr3ordinal} does not need to work with CRAN {mlr3pipelines}. If at all, {mlr3ordinal} needs to account for this. This was done by my commit above requiring mlr3pipelines dev for now. This is unrelated to mlr3pipelines.
- The missing release notes :)
