### ISSUE TITLE
export clone_with_state

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#638]
Could use it in other packages e.g. mcboost.

**Comment by mb706** [comment]
What is your intended use case? `clone_with_state()` is a helper function used internally because multiplicity handling gets easier like this. If you are using it with Multiplicities then we can export this (probably would also want to export `multiplicity_recurse()`). If you want the function for something that is not mlr3pipelines-related, then I don't think you should rely on your mlr3pipelines dependency for this kind of function.

**Comment by mb706** [comment]
I think this is too specific a function to be worth exporting. Feel free to reopen if you disagree.
