### ISSUE TITLE
po("threshold") cannot set 'prob'

### ISSUE THREAD

**Issue by loveyu3317** [mlr-org/mlr3pipelines#645]
I want to tune threshold by classif.auc. But when I run the following codes, it cannot set predict_type = "prob".
```r
gr = lrn("classif.rpart", predict_type = "prob") %>>% po("threshold") 
l = as_learner(gr) 
l$predict_type 
```

**Comment by yzm886216** [comment]
I have the same problem with you.How did you solve it?

**Comment by mb706** [comment]
The purpose of the thesholding PipeOp is specifically to turn `"prob"` predictions into `"response"` predictions. If you want to have `"prob"` predictions, you should not use the thresholding PipeOp. However, there may be a reason to have both outputs so that one could use two measures, `classif.auc` and `classif.acc`, together? We should discuss this.
