### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3pipelines#690]
Was/is the org-wide template so bad that it must be removed/overriden? Feedback is always welcome...

The current one essentially does nothing (including not helping users how to submit a "good" issue) and looks misplaced. Opening a blank issue was supported before as well via "Open a blank issue".

**Comment by mb706** [comment]
I am personally not bothered by getting "bad" issues. If someone is on the edge between submitting an issue or not submitting it, I would prefer for them to submit it. I feel like an overly imposing issue template could scare away inexperienced users, or users that are too busy to read two pages of help text just to tell me that some minor thing they don't really care about doesn't work. If the issue is missing information I can always ask for it later.

I added the blank issue template after someone at the workshop (don't remember who) told me that they were struggling to submit a short quick reminder issue to their own repo without adding reprex-code. Yes, there is the "Open a blank issue" option, but Github doesn't exactly make it prominent. It seemed bad enough to be a stumbling block for someone in our group, and I imagine that some less motivated users would have given up at that point.

There is obviously a tradeoff between keeping away or potentially improving less-useful, low-effort issues on the one side, and not putting too much of a burden on people who give us useful feedback for free on the other. The issue template policy then depends on (1) the person who has to deal with the issues and (2) the quantity of new issues. Regarding (1), I prefer getting more issues and filtering less, I can deal with ten spam issues if it gives me one more piece of useful feedback I wouldn't have gotten otherwise. Regarding (2), mlr3pipelines currently doesn't get that many new issues per week anyway. This may be different for other repos: I don't have a feel for how many issues are reported in other repos, and how much other maintainers care about quality vs. quantity. Should I get overwhelmed by too many low-quality issues in mlr3pipelines at some point, I imagine I would reinstate the org-wide template. Unfortunately, mlr3pipelines is not that popular yet :-)
