### ISSUE TITLE
Better warning if po(<id>) does not work, but ppl(<id>) exists

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3pipelines#717]
Inspired by this SO post: https://stackoverflow.com/users/17945841/programming-noob

**Comment by mb706** [comment]
Link is appears broken to me.

Since our dictionaries all inherit from the same base class, we could also think of having a central registry of all dictionaries in mlr3misc, where did_you_mean looks for similar names. So if someone wants a pipeop but uses lrn(), or wants a filter but uses po() etc., one would get a fitting hint.

**Comment by mb706** [comment]
maybe extend dictionary_sugar_get by an optional argument with alternative dicts that the user could have meant. Need to think about how the error message should look like: e.g. "Element with key 'xx' not found in DictionaryGraph! Did you mean 'xy'?\nSimilar entries in other dictionary ppl(): 'xx', 'xz'"? I.e. string similarity in same dict as before, then loop through alternative dicts and see if there are exact or near misses; if there are multiple other dicts, maybe take care direct hits are on top.

**Comment by mb706** [comment]
optoinal args of dictionary_sugar_get should have `.` prefix
