### ISSUE TITLE
Uninformative error message when SMOTE pipeop is run on data with more than one stratification column

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr3pipelines#811]
See https://stackoverflow.com/questions/78888318/how-can-i-use-smote-upsampling-with-a-categorical-variable-that-is-used-only-for

**Comment by mb706** [comment]
The issue here is that smote gives a weird error message when there are columns that were not selected by 

https://github.com/mlr-org/mlr3pipelines/blob/ee831dee1bb353e7dda018614de3630dd3046ecd/R/PipeOpSmote.R#L95

@advieser could you add a check and an informative error message there?

We are currently not doing any stratification in smote and just using the target column; but the issue for that is https://github.com/mlr-org/mlr3pipelines/issues/492
